name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Setup Fly.io CLI
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Create gemini.json file in the website/secrets folder by pulling GOOGLE_APPLICATION_CREDENTIALS
      - name: Create gemini.json from GOOGLE_APPLICATION_CREDENTIALS
        run: |
          mkdir -p ./website/secrets
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > ./website/secrets/gemini.json

      # Deploy using Fly.io, pulling the Fly API token from secrets
      - name: Deploy app with Fly.io
        run: flyctl deploy --remote-only
        working-directory: ./website
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: secrets/gemini.json